version: '3.8'

services:
  web:
    build: 
      context: ./app
      dockerfile: Dockerfile.prod
    command: gunicorn blog_app.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - static_volume:/home/app/web/staticfiles
      - media_volume:/home/app/web/mediafiles
      # - ./app/:/usr/src/app/
    expose:
      - 8000
    env_file:
      - ./.env.prod
    depends_on:
      - db
  
  db:
    image: postgres:13.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=blog_app_user
      - POSTGRES_PASSWORD=blog_app_pass
      - POSTGRES_DB=blog_app_dev
    env_file:
      - ./.env.prod.db
  
  nginx:
    build: ./nginx
    volumes:
      - static_volume:/home/app/web/staticfiles
      - media_volume:/home/app/web/mediafiles
    ports:
      - 1337:80
    depends_on:
      - web
volumes:
  postgres_data:
  static_volume:
  media_volume: